# Generated by Django 3.1.5 on 2021-01-19 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductThumb', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductDescription', models.TextField(blank=True, null=True)),
                ('ProductPrice', models.IntegerField()),
                ('ProductContact', models.CharField(max_length=14)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('Producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
